package com.masterlock.core.audit.events;

public enum EventCode {
    BATTERYLEVEL_LOW,
    FIRMWARE_UPDATE_COMPLETED,
    FIRMWARE_UPDATE_INITIATED,
    INVALID_PASSCODE_INDETERMINATE,
    INVALID_PASSCODE_MASTER,
    INVALID_PASSCODE_TEMPORARY,
    INVALID_WIRELESS_AUTHENTICATED_CMD,
    INVALID_WIRELESS_NOT_PERMITTED,
    INVALID_WIRELESS_NOT_SHEDULED,
    INVALID_WIRELESS_REPLAY,
    INVALID_WIRELESS_SESSION_TIME,
    INVALID_WIRELESS_UNAUTHENTICATED_CMD,
    INVALID_WIRELESS_UNAUTHENTICATED_USER,
    KMSDEVICEKEY_GENERATED,
    PRIVATEKEY_GENERATED,
    PRIVATEKEY_INSTALLED,
    REGISTER,
    SERVICECODE_SHARED_EMAIL,
    SERVICECODE_SHARED_SMS,
    UNAUTHORIZED_WIRELESS,
    UNLOCK_MANUAL,
    UPDATE_BATTERYLEVEL,
    UPDATE_TEMPATURE,
    UPDATE_TIMEZONE,
    TAMPER_WARNING,
    TIME_STOPPED,
    TIME_WRITTEN,
    UPDATE_FIRMWAREVERSION,
    UPDATE_LOCKMODE,
    UPDATE_PRIMARYCODE,
    UPDATE_SECONDARYCODE,
    UPDATE_RELOCKINTERVAL,
    GUEST_INVITE_GENERATED,
    DOOR_OPENED,
    SHACKLE_OPENED("SHACKLE_REMOVED"),
    LOCK_OPENED,
    RELOCK_AUTOMATIC_DOOR("DOOR_AUTOMATIC_RELOCK"),
    RELOCK_AUTOMATIC_SHACKLE("SHACKLE_AUTOMATIC_RELOCK"),
    RELOCK_AUTOMATIC,
    RELOCK_MANUAL_DOOR("DOOR_LOCKED"),
    RELOCK_MANUAL_SHACKLE("SHACKLE_LOCKED"),
    RELOCK_MANUAL,
    UNLOCK_WIRELESS_DOOR("DOOR_UNLOCKED_BLUETOOTH"),
    UNLOCK_WIRELESS_SHACKLE("SHACKLE_UNLOCKED_BLUETOOTH"),
    UNLOCK_WIRELESS,
    UNLOCK_DOOR_MASTERCODE("DOOR_UNLOCKED_BACKUPMASTERCODE"),
    UNLOCK_DOOR_PRIMARYCODE("DOOR_UNLOCKED_PRIMARYCODE"),
    UNLOCK_DOOR_SERVICECODE("DOOR_UNLOCKED_TEMPORARYCODE"),
    UNLOCK_SECONDARY_PASSCODE("DOOR_UNLOCKED_SECONDARYCODE"),
    UNLOCK_SHACKLE_MASTERCODE("SHACKLE_UNLOCKED_BACKUPMASTERCODE"),
    UNLOCK_SHACKLE_PRIMARYCODE("SHACKLE_UNLOCKED_PRIMARYCODE"),
    UNLOCK_MASTERCODE,
    UNLOCK_PRIMARYCODE,
    UNLOCK_SERVICECODE,
    SECONDARYCODE_CREATED,
    SECONDARYCODE_CHANGED,
    SECONDARYCODE_DELETED,
    SECONDARYCODE_SHARED,
    TEMPORARYCODE_SHARED,
    TEMPORARYCODE_FUTURE_SHARED,
    DEMO_MODE_ENABLED,
    DEMO_MODE_DISABLED,
    UPDATE_LAST_KNOWN_LOCATION,
    CLEAR_LAST_KNOWN_LOCATION;
    
    final String eventName;

    private EventCode(String str) {
        this.eventName = str;
    }

    private String getName() {
        return this.eventName;
    }

    public String toString() {
        return getName();
    }

    public static EventCode getEventCode(String str) {
        EventCode[] values;
        for (EventCode eventCode : values()) {
            if (eventCode.eventName.equalsIgnoreCase(str)) {
                return eventCode;
            }
        }
        return null;
    }
}
